version: '3.7'

services:
  arbiter:
    image: containers.intersystems.com/intersystems/arbiter:2021.1.0.215.0
    init: true
    command: 
      - /usr/local/etc/irissys/startISCAgent.sh 2188
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  master:
    build: .
    image: demoapp
    networks:
      app_net:
        ipv4_address: 172.16.238.20
    environment: 
      - IRIS_MIRROR_ROLE=master
      - IRIS_MIRROR_ARBITER=172.16.238.10
    ports:
      - 81:52773
    volumes: 
      - ./iris.key:/usr/irissys/mgr/iris.key
      - ./backup:/opt/backup
      - ./init_mirror.sh:/init_mirror.sh
    hostname: master

  backup:
    image: demoapp
    networks:
      app_net:
        ipv4_address: 172.16.238.30
    ports:
      - 82:52773
    environment: 
      - IRIS_MIRROR_ROLE=backup
      - IRIS_MIRROR_AGENT=172.16.238.20
    volumes: 
      - ./iris.key:/usr/irissys/mgr/iris.key
      - ./backup:/opt/backup
      - ./init_mirror.sh:/init_mirror.sh
    hostname: backup
  
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

volumes:
  backup:
    
